name: "Terraform"
on: workflow_dispatch
# on:
#   schedule:
#     - cron:  '0 0 * * *'
#   push:
#     branches:
#       - main
#   pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}

jobs:
  terraform_module:
    name: "Apply permission"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0
      - name: Download Private Modules Terraform 
        run: git config --global url."https://oauth2:${{ secrets.TF_GITHUB_TOKEN }}@github.com".insteadOf https://github.com
      # - name: Download Private Modules Terraform 
      #   uses: actions/checkout@v4
      #   with:
      #     repository: campos-pay/devops-github-module
      #     token: ${{ secrets.TF_GITHUB_TOKEN }}
      #     # ref: 'dev'

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -out tfplan
        
      - name: Terraform Apply
        id: apply
        run: terraform apply "tfplan"
